# Generated by Django 3.1 on 2020-08-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0002_auto_20200822_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor_name', models.CharField(default='', max_length=100)),
                ('Actor_photo', models.ImageField(upload_to='mainwebsite/uploadimages/actors')),
            ],
        ),
    ]
