# Generated by Django 3.1 on 2020-08-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(default='', max_length=100)),
                ('movie_language', models.CharField(default='', max_length=100)),
                ('movie_Type', models.CharField(default='', max_length=100)),
                ('movie_duration', models.CharField(default='', max_length=100)),
                ('movie_likes', models.CharField(default='', max_length=100)),
                ('movie_Audience_score', models.CharField(default='', max_length=100)),
                ('movie_Rattings', models.CharField(default='', max_length=100)),
                ('movie_summery', models.TextField(default='', max_length=100000)),
                ('movie_Actors', models.ManyToManyField(default='', to='mainwebsite.Actors')),
                ('movie_relase_hall', models.ManyToManyField(default='', to='mainwebsite.Moviehalls')),
                ('movie_screen_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.allowscreens')),
            ],
        ),
    ]
