# Generated by Django 3.1 on 2020-08-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0004_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_big_banner',
            field=models.ImageField(default='', upload_to='mainwebsite/uploadimages/movies/banner'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photo1',
            field=models.ImageField(default='', upload_to='mainwebsite/uploadimages/movies/photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photo2',
            field=models.ImageField(default='', upload_to='mainwebsite/uploadimages/movies/photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_photo3',
            field=models.ImageField(default='', upload_to='mainwebsite/uploadimages/movies/photos'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_thumbnil',
            field=models.ImageField(default='', upload_to='mainwebsite/uploadimages/movies/thumbnil'),
        ),
    ]
