# Generated by Django 3.1 on 2020-08-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0005_auto_20200823_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(default='', max_length=100)),
                ('Event_date', models.DateField(default='')),
                ('Event_address', models.CharField(default='', max_length=100)),
                ('Event_email', models.CharField(default='', max_length=100)),
                ('Event_summery', models.TextField(default='', max_length=100000)),
                ('Event_thumbnil', models.ImageField(default='', upload_to='mainwebsite/uploadimages/event/thumbnil')),
                ('Event_big_banner', models.ImageField(default='', upload_to='mainwebsite/uploadimages/event/banner')),
            ],
        ),
    ]
