# Generated by Django 3.1 on 2020-08-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0007_seatbookedformovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_phone_no', models.CharField(default='', max_length=100)),
                ('user_emailid', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_booked_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(default='', max_length=100)),
                ('Time_slot', models.CharField(default='', max_length=100)),
                ('Each_ticke_tprice', models.CharField(default='', max_length=100)),
                ('Total_ticket_price', models.CharField(default='', max_length=100)),
                ('Total_seats', models.CharField(default='', max_length=100)),
                ('Seat_numbers', models.CharField(default='', max_length=100)),
                ('Booeked_time', models.DateTimeField(auto_now_add=True)),
                ('Is_user_visited', models.BooleanField(default=False, verbose_name='Is User Visited Movie')),
                ('Selected_hall', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.moviehalls')),
                ('Selected_movie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.movie')),
                ('User', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainwebsite.users')),
            ],
        ),
    ]
