# Generated by Django 3.1 on 2020-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0008_movie_booked_by_user_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_booked_by_user',
            name='user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie_booked_by_user',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie_booked_by_user',
            name='user_phone_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
